'use client'

import useSWR from 'swr'
import { useMemo, useState } from 'react'
import { BookOpen, Code2, Database, GitBranch, Heart, Home, Menu, Moon, Search, Sparkles, Star, Sun, TrendingUp, Trophy, Users, X, Zap } from 'lucide-react'

type Repo = { id: number; fullName: string; description: string | null; language: string; stars: number; forks: number; updatedAt: string; htmlUrl: string; avatar?: string }
const fetcher = (url: string) => fetch(url).then((r) => { if (!r.ok) throw new Error('Search failed'); return r.json() })
const formatNumber = (value: number) => value.toLocaleString('en-US')
const categories = [['Web dasturlash', 'web'], ['Mobil ilovalar', 'mobile'], ['Telegram botlar', 'telegram'], ['Sun’iy intellekt', 'ai'], ['O‘yinlar', 'game'], ['Ma’lumotlar bazasi', 'database'], ['DevOps', 'devops']] as const
const nav = [['Bosh sahifa', Home], ['Qidiruv', Search], ['Trenddagi loyihalar', TrendingUp], ['Top toifalar', Trophy], ['Saqlanganlar', Heart], ['Mening profilim', Users]] as const

export default function RepoDashboard() {
  const [query, setQuery] = useState('')
  const [submitted, setSubmitted] = useState('')
  const [language, setLanguage] = useState('Barchasi')
  const [stars, setStars] = useState('Barchasi')
  const [pushed, setPushed] = useState('Istalgan vaqtda')
  const [sort, setSort] = useState('Eng ko‘p yulduzli')
  const [activeNav, setActiveNav] = useState('Bosh sahifa')
  const [mobileNav, setMobileNav] = useState(false)
  const [dark, setDark] = useState(false)
  const [applied, setApplied] = useState({ language: 'Barchasi', stars: 'Barchasi', pushed: 'Istalgan vaqtda', sort: 'Eng ko‘p yulduzli' })
  const params = new URLSearchParams({ q: submitted || 'stars:>1000', language: applied.language, stars: applied.stars, pushed: applied.pushed, sort: applied.sort })
  const { data, error, isLoading } = useSWR<{ total: number; items: Repo[] }>(`/api/repos?${params}`, fetcher, { keepPreviousData: true, revalidateOnFocus: false })
  const rows = useMemo(() => data?.items ?? [], [data])
  const search = () => setSubmitted(query.trim())
  const apply = () => { setApplied({ language, stars, pushed, sort }); setSubmitted(query.trim()) }
  const reset = () => { setQuery(''); setSubmitted(''); setLanguage('Barchasi'); setStars('Barchasi'); setPushed('Istalgan vaqtda'); setSort('Eng ko‘p yulduzli'); setApplied({ language: 'Barchasi', stars: 'Barchasi', pushed: 'Istalgan vaqtda', sort: 'Eng ko‘p yulduzli' }) }
  const chooseCategory = (value: string) => { setQuery(value); setSubmitted(value); setActiveNav('Qidiruv'); setMobileNav(false) }
  return <div className={dark ? 'app-shell dark-mode' : 'app-shell'}>
    <aside className={mobileNav ? 'sidebar mobile-open' : 'sidebar'}><div className="sidebar-top"><strong className="brand">Repo<span>Qidiruv</span></strong><button className="icon-button mobile-close" aria-label="Menyuni yopish" onClick={() => setMobileNav(false)}><X /></button></div><nav className="nav-list" aria-label="Asosiy menyu">{nav.map(([label, Icon]) => <button className={activeNav === label ? 'nav-item active' : 'nav-item'} key={label} onClick={() => { setActiveNav(label); setMobileNav(false) }}><Icon /><span>{label}</span></button>)}</nav><div className="sidebar-section"><p className="eyebrow">KATEGORIYALAR</p>{categories.map(([label, value]) => <button className="nav-item" key={label} onClick={() => chooseCategory(value)}><Code2 /><span>{label}</span></button>)}</div><div className="token-card"><strong>GitHub token ulang</strong><p>Ko‘proq natija va cheklanmagan qidiruv uchun tokeningizni ulang.</p><button onClick={() => alert('GitHub token ulash tez orada mavjud bo‘ladi')}>Ulash</button></div></aside>
    <div className="main-area"><header className="topbar"><button className="icon-button menu-button" aria-label="Menyuni ochish" onClick={() => setMobileNav(true)}><Menu /></button><form className="search-wrap" onSubmit={(e) => { e.preventDefault(); search() }}><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Loyiha nomi, texnologiya yoki kalit so‘z..." aria-label="Loyiha qidirish" /><button type="submit">Qidirish</button></form><div className="top-actions"><button className="icon-button" aria-label="Temani almashtirish" onClick={() => setDark((v) => !v)}>{dark ? <Sun /> : <Moon />}</button><div className="avatar">S</div></div></header><main className="content"><section className="welcome"><div><h1>{activeNav === 'Qidiruv' ? 'Loyihalarni qidiring' : 'Xush kelibsiz, Sardor!'}</h1><p>GitHub’dan eng yaxshi loyihalarni tez toping va kashf qiling.</p></div></section><section className="stats-grid">{[['Jami loyihalar', formatNumber(data?.total || 12540786), BookOpen], ['Yulduzlar', '3 245 987', Star], ['Forklar', '1 125 654', GitBranch], ['Dasturchilar', '578 920', Code2]].map(([label, value, Icon]) => <div className="stat-card" key={label as string}><div className="stat-icon"><Icon /></div><div><strong>{value as string}</strong><h3>{label as string}</h3><p>GitHub ma’lumotlari</p></div></div>)}</section><section className="section-block recent"><div className="section-heading"><h2>{submitted ? `“${submitted}” natijalari` : 'Trenddagi loyihalar'}</h2><span>{(data?.total ? formatNumber(data.total) : '0')} ta loyiha</span></div><div className="table-card"><div className="table-head"><span>Loyiha nomi</span><span>Til</span><span>Yulduzlar</span><span>Yangilangan</span></div>{isLoading && <div className="empty-row">Loyihalar yuklanmoqda...</div>}{error && <div className="empty-row">GitHub API bilan bog‘lanishda xatolik. Qayta urinib ko‘ring.</div>}{rows.map((repo) => <div className="table-row" key={repo.id}><div className="repo-name"><div className="repo-mini">{repo.avatar ? <img src={repo.avatar} alt="" /> : <Code2 />}</div><div><a href={repo.htmlUrl} target="_blank" rel="noreferrer">{repo.fullName}</a><small>{repo.description || 'Tavsif mavjud emas'}</small></div></div><div className="table-language"><i />{repo.language}</div><span><Star /> {repo.stars.toLocaleString()}</span><span>{new Date(repo.updatedAt).toLocaleDateString('uz-UZ')}</span></div>)}{!isLoading && !error && !rows.length && <div className="empty-row">Qidiruv bo‘yicha loyiha topilmadi.</div>}</div></section></main></div>
    <aside className="right-rail"><div className="filter-card"><div className="rail-heading"><h2>Qidiruv filtrlari</h2><button onClick={reset}>Tozalash</button></div><label>Dasturlash tili<select value={language} onChange={(e) => setLanguage(e.target.value)}><option>Barchasi</option><option>JavaScript</option><option>Python</option><option>TypeScript</option><option>Java</option></select></label><label>Yulduzlar soni<select value={stars} onChange={(e) => setStars(e.target.value)}><option>Barchasi</option><option value="1000">1 000+</option><option value="10000">10 000+</option><option value="50000">50 000+</option></select></label><label>Yangilangan vaqti<select value={pushed} onChange={(e) => setPushed(e.target.value)}><option>Istalgan vaqtda</option><option value="2026-09-02">Bugun</option><option value="2026-08-27">Bu hafta</option></select></label><label>Saralash<select value={sort} onChange={(e) => setSort(e.target.value)}><option>Eng ko‘p yulduzli</option><option>Eng yangi</option></select></label><button className="apply-button" onClick={apply}>Filtrni qo‘llash</button></div><div className="rail-card"><h2>Tezkor kategoriyalar</h2>{categories.slice(0, 5).map(([name, value]) => <button className="rail-row rail-action" key={name} onClick={() => chooseCategory(value)}><span><Sparkles />{name}</span><span>Qidirish</span></button>)}</div></aside>
  </div>
}
